import type { Metadata } from "next";
import Script from "next/script";
import { mulish } from "@/lib/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} font-sans`}>
        {children}
        <noscript
          dangerouslySetInnerHTML={{
            __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=${process.env.GTM_ID}"
          height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
          }}
        />
        <Script src={process.env.INTERACTIVE_STUDIO_BEACON_SCRIPT} strategy="beforeInteractive" />
        {process.env.NEW_RELIC_SCRIPT && <Script src={process.env.NEW_RELIC_SCRIPT} strategy="beforeInteractive" />}
        <Script id="gtm-script" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];
              w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js', });
              var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
              j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl+'&gtm_auth=&gtm_preview=&gtm_cookies_win=x';
              f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','${process.env.GTM_ID}');
          `}
        </Script>
      </body>
    </html>
  );
}
